// generatePdfMap.js
const fs = require("fs");
const path = require("path");

const pdfDir = path.join(__dirname, "assets", "pdfs");
const outputPath = path.join(__dirname, "pdfMap.ts");

const files = fs.readdirSync(pdfDir).filter(file => file.endsWith(".pdf"));

const mapEntries = files.map(file => {
  return `"${file}": require("./assets/pdfs/${file}")`;
});

const content = `// Auto-generated by generatePdfMap.js
export const pdfMap: Record<string, number> = {
  ${mapEntries.join(",\n  ")}
};
`;

fs.writeFileSync(outputPath, content, "utf8");

console.log(`✅ pdfMap.ts generated with ${files.length} PDF(s).`);
